[package]
name = "null-api"
version = "0.1.0"
edition = "2021"
author = "Stephen F<stephen@thenull.dev>"

[dependencies]
actix-web = "4"
env_logger = "0.10.0"
log = "0.4"
reqwest = "0.11.13"
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0.147", features= ["derive"] }
serde_json = "1.0.89"
redis = {version ="0.22.1", features = ["tokio-comp", "connection-manager"]}
envconfig = "0.10.0"

[dependencies.sea-orm]
version = "0.10.4" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-postgres",
]