name: Docker Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-null-api:
    runs-on: self-hosted
    strategy:
      matrix:
        redis-version: [4, 5, 6]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the null-api Docker image
        run: |
            docker build . --tag ghcr.io/thenulldev/api:latest
            docker run ghcr.io/thenulldev/api:latest
            docker push ghcr.io/thenulldev/api:latest
