name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  DEPLOYMENT_ID: null-api

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the null-api Docker image
        run: |
            docker build . --tag ghcr.io/thenulldev/api:${{ github.sha }}
            docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
            docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
            docker push ghcr.io/thenulldev/api:latest
